server {
      listen 443 ssl default_server;
      listen [::]:443 ssl default_server;

      server_name ookamonu.42.fr www.ookamonu.42.fr;

	  ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
	  ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
	  ssl_protocols TLSv1.3 TLSv1.2;

      root /var/www/html;
      index index.php;

      location / {
            index index.php;
      }
      location ~ \.php$ {
            try_files $uri /index.php =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass wordpress-site:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      }
}






### this configuration sets up an nginx server to serve the WordPress site. It listens on port 443 for HTTPS
      # connections, uses SSL certificates for secure communication, and sets up the root directory for the site.

# - listens on port 443 for both IPv4 and IPv6 connections, using SSL.
# - sets the server name for the site.
# - specifies the SSL certificate and key files for secure connections.
# - sets the root directory where the site files are located.
# - defines the index file to serve when a directory is requested.
# - configures the root location to serve index.php by default.
# - handles PHP files:
#    - tries to serve the requested file, if not found, it serves index.php or returns a 404 error.
#    - splits the path info for PHP scripts.
#    - passes PHP requests to the FastCGI server running on 'wordpress-site' at port 9000.
#    - includes additional FastCGI parameters for PHP processing.
#    - sets the SCRIPT_FILENAME parameter to ensure PHP scripts are executed correctly.
