version: '3.8'

services:
  nginx-42:
    build: ./requirements/nginx
    image: nginx-42
    container_name: nginx-42
    ports: [ "443:443" ]
    depends_on: [ "wordpress-site" ]
    volumes: [ "wordvol:/var/www/html" ]
    networks: [ "inception" ]
    restart: always

  mariadb-data:
    build: ./requirements/mariadb
    image: mariadb-data
    container_name: mariadb-data
    env_file: [ ".env" ]
    volumes: [ "mariavol:/var/lib/mysql" ]
    networks: [ "inception" ]
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 5s
  
  wordpress-site:
    build: ./requirements/wordpress
    image: wordpress-site
    container_name: wordpress-site
    env_file: [ ".env" ]
    depends_on:
      mariadb-data:
        condition: service_healthy
    volumes: [ "wordvol:/var/www/html" ]
    networks: [ "inception" ]
    restart: always

# ======================================== #
  redis:
    build: ./requirements/redis
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  ftp:
    build: ./requirements/ftp
    image: ftp
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - "wordvol:/home/vsftpd"
    networks:
      - inception
    restart: always

  static-site:
    build: ./requirements/static
    image: static-site
    container_name: static-site
    ports:
      - "8080:80"
    networks:
      - inception
    restart: always

  adminer:
    build: ./requirements/adminer
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    networks:
      - inception
    restart: always

  phpmyadmin:
    build: ./requirements/phpmyadmin
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mariadb-data
    networks:
      - inception
    restart: always

# ======================================== #

volumes:
  mariavol: { name: mariavol, driver_opts: { type: none, device: /home/ookamonu/data/mariadb_data, o: bind } }
  wordvol: { name: wordvol, driver_opts: { type: none, device: /home/ookamonu/data/wordpress_data, o: bind } }

networks:
  inception: { name: inception }
